### ISSUE TITLE
cigar string

### ISSUE THREAD

**Issue by gorliver** [ITBE-Lab/MA#4]
Hi Arne and Markus,
Thank you for the tool and I really enjoy the speed of MA.
I have a pipeline which relays one the CIGAR string of the sam file. The cigar string of MA output is like "2=3X2=1X1=4D5=1X7=3X4=1X5=1X6=1X1=4D2=3D10=3D2=3I1=1D5=2X4=2I" and it's not compatible with my current pipeline. I wonder if there is a way or instruction to convert the CIGAR string to the standard format like minimap2?
Thank you,
Gorliver

**Comment by MarkusRainerSchmidt** [comment]
Hello Gorliver,

I assume the problem is the ambiguity in the SAM-format with respect to the M-operation and the “=,X”-operations (which allows distinguishing between match and mismatch in contrast to the M-operation). By default, MA writes SAM-files using the “=,X”-operations. We added a new option Use_M_in_CIGAR to MA for forcing M-operation based SAM-output. Therefore, please clone the newest version of MA and add ‘--Use_M_in_CIGAR true’ to your command line. If you still have problems with your SAM-files, please let me know. 

Best wishes,
Markus

**Comment by gorliver** [comment]
Hi Markus,
Thanks for the option!
